# Generated by Django 3.2.7 on 2021-09-24 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
