# Generated by Django 3.2.7 on 2021-09-25 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_supplies_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
