# Generated by Django 3.2.7 on 2021-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Supplies',
            field=models.ManyToManyField(blank=True, to='pet.Supplies'),
        ),
    ]
