# Generated by Django 3.2.7 on 2021-09-24 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinc_name', models.CharField(blank=True, max_length=70, null=True)),
                ('location', models.TextField(blank=True, max_length=500, null=True)),
                ('starthoure', models.TimeField(help_text='Hour:Minute')),
                ('endhoure', models.TimeField(help_text='Hour:Minute')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('picture', models.ImageField(blank=True, upload_to='clinc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
