# Generated by Django 3.2.7 on 2021-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='endhoure',
            field=models.TimeField(blank=True, help_text='Hour:Minute'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='starthoure',
            field=models.TimeField(blank=True, help_text='Hour:Minute'),
        ),
    ]
